# Generated by Django 3.2.9 on 2021-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_colaborador_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='endereco_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.endereco'),
        ),
    ]
