# Generated by Django 3.2.9 on 2021-11-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_auto_20211119_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDepartamento', models.CharField(max_length=20)),
                ('diretorDepartmento', models.CharField(max_length=20)),
                ('qntFuncionario', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colaboradores.departamento'),
        ),
    ]
